# Generated by Django 4.2.7 on 2023-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=20)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expense_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(max_length=20)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('income_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
